name: Deploy Shiny App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up python 
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"
        
    - name: Install rsconnect-python
      run: pip install rsconnect-python

    - name: Deploy to shinyapps.io
      env:
        SHINYAPPS_TOKEN: ${{ secrets.SHINYAPPS_TOKEN }}
        SHINYAPPS_SECRET: ${{ secrets.SHINYAPPS_SECRET }}
        GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
      run: |
        rsconnect add --account piero-palacios --name piero-palacios --token ${SHINYAPPS_TOKEN} --secret ${SHINYAPPS_SECRET}
        rsconnect deploy shiny . --name piero-palacios --title gemini_chatbot
